"""table du contexte I creation d entreprise

Révision : 982080daa6fd
Précédente : 0b1987f66324
Créée le : 2026-08-17 14:20:57.667341
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '982080daa6fd'
down_revision: str | None = '0b1987f66324'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dossier_creation',
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('etape', sa.String(length=30), nullable=False),
    sa.Column('immobile_depuis', sa.Date(), nullable=False),
    sa.Column('denomination_souhaitee', sa.String(length=255), nullable=False),
    sa.Column('converti_en', sa.String(length=20), nullable=True),
    sa.Column('locataire', sa.String(length=64), nullable=False),
    sa.Column('donnees', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_dossier_creation'))
    )
    op.create_index('ix_dossier_creation_pipeline', 'dossier_creation', ['locataire', 'etape', 'immobile_depuis'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """⚠️ Une migration qui supprime des données ne se défait pas : `downgrade`
    rétablit le schéma, jamais le contenu. Sur les tables append-only — journal
    d'audit, accusés de réception —, il n'y a **rien** à défaire."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dossier_creation_pipeline', table_name='dossier_creation')
    op.drop_table('dossier_creation')
    # ### end Alembic commands ###
