"""contextes metier

Révision : 123ec75ca4b0
Précédente : 44356d656d73
Créée le : 2026-08-15 23:59:54.804475
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '123ec75ca4b0'
down_revision: str | None = '44356d656d73'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demande_piece',
    sa.Column('identifiant', sa.String(length=64), nullable=False),
    sa.Column('entreprise', sa.String(length=20), nullable=False),
    sa.Column('type_attendu', sa.String(length=40), nullable=False),
    sa.Column('statut', sa.String(length=32), nullable=False),
    sa.Column('demandee_le', sa.Date(), nullable=False),
    sa.Column('attendue_pour', sa.Date(), nullable=True),
    sa.Column('bloquante', sa.Boolean(), nullable=False),
    sa.Column('locataire', sa.String(length=64), nullable=False),
    sa.Column('donnees', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('identifiant', name=op.f('pk_demande_piece'))
    )
    op.create_index('ix_demande_attendue_pour', 'demande_piece', ['locataire', 'attendue_pour'], unique=False)
    op.create_index('ix_demande_dossier_statut', 'demande_piece', ['locataire', 'entreprise', 'statut'], unique=False)
    op.create_table('devis',
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('courriel', sa.String(length=320), nullable=False),
    sa.Column('etabli_le', sa.Date(), nullable=False),
    sa.Column('valide_jusqu_au', sa.Date(), nullable=False),
    sa.Column('etat', sa.String(length=20), nullable=False),
    sa.Column('locataire', sa.String(length=64), nullable=False),
    sa.Column('donnees', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_devis'))
    )
    op.create_index('ix_devis_courriel', 'devis', ['locataire', 'courriel'], unique=False)
    op.create_table('ecriture',
    sa.Column('locataire', sa.String(length=64), nullable=False),
    sa.Column('entreprise', sa.String(length=20), nullable=False),
    sa.Column('exercice', sa.String(length=10), nullable=False),
    sa.Column('journal', sa.String(length=10), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('date_operation', sa.Date(), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('etat', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('piece_justificative', sa.String(length=64), nullable=True),
    sa.Column('donnees', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('locataire', 'entreprise', 'exercice', 'journal', 'numero', name=op.f('pk_ecriture'))
    )
    op.create_index('ix_ecriture_date', 'ecriture', ['locataire', 'entreprise', 'date_operation'], unique=False)
    op.create_index('ix_ecriture_dossier_exercice', 'ecriture', ['locataire', 'entreprise', 'exercice'], unique=False)
    op.create_index('ix_ecriture_piece', 'ecriture', ['locataire', 'piece_justificative'], unique=False)
    op.create_table('entreprise',
    sa.Column('niu', sa.String(length=20), nullable=False),
    sa.Column('denomination', sa.String(length=255), nullable=False),
    sa.Column('forme_juridique', sa.String(length=20), nullable=False),
    sa.Column('date_creation', sa.Date(), nullable=False),
    sa.Column('activite', sa.String(length=255), nullable=True),
    sa.Column('siege', sa.String(length=255), nullable=True),
    sa.Column('locataire', sa.String(length=64), nullable=False),
    sa.Column('donnees', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('niu', name=op.f('pk_entreprise'))
    )
    op.create_index('ix_entreprise_denomination', 'entreprise', ['locataire', 'denomination'], unique=False)
    op.create_table('paiement',
    sa.Column('identifiant', sa.String(length=64), nullable=False),
    sa.Column('souscription', sa.String(length=64), nullable=False),
    sa.Column('cle_idempotence', sa.String(length=64), nullable=False),
    sa.Column('echeance', sa.String(length=80), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('montant', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('initie_le', sa.DateTime(), nullable=False),
    sa.Column('reference_externe', sa.String(length=120), nullable=True),
    sa.Column('locataire', sa.String(length=64), nullable=False),
    sa.Column('donnees', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('identifiant', name=op.f('pk_paiement')),
    sa.UniqueConstraint('locataire', 'cle_idempotence', name='uq_paiement_locataire_cle'),
    sa.UniqueConstraint('locataire', 'echeance', name='uq_paiement_locataire_echeance')
    )
    op.create_index('ix_paiement_reference_externe', 'paiement', ['locataire', 'reference_externe'], unique=False)
    op.create_index('ix_paiement_souscription', 'paiement', ['locataire', 'souscription'], unique=False)
    op.create_index('ix_paiement_statut', 'paiement', ['locataire', 'statut', 'initie_le'], unique=False)
    op.create_index('ix_paiement_telephone', 'paiement', ['locataire', 'telephone', 'initie_le'], unique=False)
    op.create_table('piece_justificative',
    sa.Column('identifiant', sa.String(length=64), nullable=False),
    sa.Column('entreprise', sa.String(length=20), nullable=False),
    sa.Column('canal', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('etat', sa.String(length=32), nullable=False),
    sa.Column('depose_le', sa.Date(), nullable=False),
    sa.Column('recue_le', sa.DateTime(), nullable=False),
    sa.Column('empreinte', sa.String(length=64), nullable=True),
    sa.Column('reference_document', sa.String(length=120), nullable=True),
    sa.Column('date_document', sa.Date(), nullable=True),
    sa.Column('montant_ttc', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('emetteur', sa.String(length=255), nullable=True),
    sa.Column('reference_ecriture', sa.String(length=64), nullable=True),
    sa.Column('locataire', sa.String(length=64), nullable=False),
    sa.Column('donnees', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('identifiant', name=op.f('pk_piece_justificative'))
    )
    op.create_index('ix_piece_dossier_etat', 'piece_justificative', ['locataire', 'entreprise', 'etat'], unique=False)
    op.create_index('ix_piece_empreinte', 'piece_justificative', ['locataire', 'empreinte'], unique=False)
    op.create_index('ix_piece_recue_le', 'piece_justificative', ['locataire', 'recue_le'], unique=False)
    op.create_table('plan_imputation',
    sa.Column('locataire', sa.String(length=64), nullable=False),
    sa.Column('entreprise', sa.String(length=20), nullable=False),
    sa.Column('donnees', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('locataire', 'entreprise', name=op.f('pk_plan_imputation'))
    )
    op.create_table('souscription',
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('devis', sa.String(length=64), nullable=False),
    sa.Column('service', sa.String(length=40), nullable=False),
    sa.Column('etat', sa.String(length=30), nullable=False),
    sa.Column('montant', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('engagee_le', sa.DateTime(), nullable=False),
    sa.Column('payee_le', sa.DateTime(), nullable=True),
    sa.Column('niu', sa.String(length=20), nullable=True),
    sa.Column('compte', sa.String(length=64), nullable=True),
    sa.Column('prend_effet_le', sa.Date(), nullable=True),
    sa.Column('locataire', sa.String(length=64), nullable=False),
    sa.Column('donnees', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_souscription'))
    )
    op.create_index('ix_souscription_etat', 'souscription', ['locataire', 'etat'], unique=False)
    op.create_index('ix_souscription_niu', 'souscription', ['locataire', 'niu'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """⚠️ Une migration qui supprime des données ne se défait pas : `downgrade`
    rétablit le schéma, jamais le contenu. Sur les tables append-only — journal
    d'audit, accusés de réception —, il n'y a **rien** à défaire."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_souscription_niu', table_name='souscription')
    op.drop_index('ix_souscription_etat', table_name='souscription')
    op.drop_table('souscription')
    op.drop_table('plan_imputation')
    op.drop_index('ix_piece_recue_le', table_name='piece_justificative')
    op.drop_index('ix_piece_empreinte', table_name='piece_justificative')
    op.drop_index('ix_piece_dossier_etat', table_name='piece_justificative')
    op.drop_table('piece_justificative')
    op.drop_index('ix_paiement_telephone', table_name='paiement')
    op.drop_index('ix_paiement_statut', table_name='paiement')
    op.drop_index('ix_paiement_souscription', table_name='paiement')
    op.drop_index('ix_paiement_reference_externe', table_name='paiement')
    op.drop_table('paiement')
    op.drop_index('ix_entreprise_denomination', table_name='entreprise')
    op.drop_table('entreprise')
    op.drop_index('ix_ecriture_piece', table_name='ecriture')
    op.drop_index('ix_ecriture_dossier_exercice', table_name='ecriture')
    op.drop_index('ix_ecriture_date', table_name='ecriture')
    op.drop_table('ecriture')
    op.drop_index('ix_devis_courriel', table_name='devis')
    op.drop_table('devis')
    op.drop_index('ix_demande_dossier_statut', table_name='demande_piece')
    op.drop_index('ix_demande_attendue_pour', table_name='demande_piece')
    op.drop_table('demande_piece')
    # ### end Alembic commands ###
