"""tables du contexte G social et paie

Révision : 438e6c427226
Précédente : 982080daa6fd
Créée le : 2026-08-17 15:52:27.199588
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '438e6c427226'
down_revision: str | None = '982080daa6fd'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrat_travail',
    sa.Column('identifiant', sa.String(length=60), nullable=False),
    sa.Column('salarie', sa.String(length=40), nullable=False),
    sa.Column('entreprise', sa.String(length=20), nullable=False),
    sa.Column('debut', sa.Date(), nullable=False),
    sa.Column('fin', sa.Date(), nullable=True),
    sa.Column('locataire', sa.String(length=64), nullable=False),
    sa.Column('donnees', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('identifiant', name=op.f('pk_contrat_travail'))
    )
    op.create_index('ix_contrat_dossier_periode', 'contrat_travail', ['locataire', 'entreprise', 'debut', 'fin'], unique=False)
    op.create_index('ix_contrat_salarie', 'contrat_travail', ['locataire', 'salarie', 'debut'], unique=False)
    op.create_table('salarie',
    sa.Column('matricule', sa.String(length=40), nullable=False),
    sa.Column('entreprise', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('prenom', sa.String(length=120), nullable=False),
    sa.Column('matricule_cnps', sa.String(length=40), nullable=True),
    sa.Column('locataire', sa.String(length=64), nullable=False),
    sa.Column('donnees', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('matricule', name=op.f('pk_salarie'))
    )
    op.create_index('ix_salarie_dossier', 'salarie', ['locataire', 'entreprise', 'nom'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """⚠️ Une migration qui supprime des données ne se défait pas : `downgrade`
    rétablit le schéma, jamais le contenu. Sur les tables append-only — journal
    d'audit, accusés de réception —, il n'y a **rien** à défaire."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_salarie_dossier', table_name='salarie')
    op.drop_table('salarie')
    op.drop_index('ix_contrat_salarie', table_name='contrat_travail')
    op.drop_index('ix_contrat_dossier_periode', table_name='contrat_travail')
    op.drop_table('contrat_travail')
    # ### end Alembic commands ###
