"""socle : comptes habilitations jetons sessions audit accuses

Révision : 44356d656d73
Précédente : 
Créée le : 2026-08-15 23:37:34.433636
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '44356d656d73'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accuse_reception',
    sa.Column('numero', sa.String(length=120), nullable=False),
    sa.Column('portail', sa.String(length=40), nullable=False),
    sa.Column('reference_document', sa.String(length=255), nullable=False),
    sa.Column('depose_le', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('empreinte_deposee', sa.String(length=64), nullable=False),
    sa.Column('depose_par', sa.String(length=64), nullable=False),
    sa.Column('montant_constate', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('piece_jointe', sa.String(length=255), nullable=True),
    sa.Column('precision', sa.Text(), nullable=True),
    sa.Column('contenu_depose', sa.Text(), nullable=True),
    sa.Column('verifie', sa.Boolean(), nullable=False),
    sa.Column('locataire', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('numero', name=op.f('pk_accuse_reception')),
    sa.UniqueConstraint('locataire', 'reference_document', name='uq_accuse_reception_locataire_reference')
    )
    op.create_index('ix_accuse_reception_portail', 'accuse_reception', ['locataire', 'portail', 'depose_le'], unique=False)
    op.create_table('compte',
    sa.Column('identifiant', sa.String(length=64), nullable=False),
    sa.Column('courriel', sa.String(length=320), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('prenom', sa.String(length=120), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('empreinte_mot_de_passe', sa.String(length=255), nullable=True),
    sa.Column('secret_totp', sa.String(length=64), nullable=True),
    sa.Column('etat', sa.String(length=32), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('tentatives_echouees', sa.Integer(), nullable=False),
    sa.Column('verrouille_jusqu_a', sa.DateTime(), nullable=True),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.Column('locataire', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('identifiant', name=op.f('pk_compte')),
    sa.UniqueConstraint('locataire', 'courriel', name='uq_compte_locataire_courriel')
    )
    op.create_index('ix_compte_locataire_etat', 'compte', ['locataire', 'etat'], unique=False)
    op.create_table('journal_audit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rang', sa.BigInteger(), nullable=False),
    sa.Column('horodatage', sa.DateTime(), nullable=False),
    sa.Column('acteur', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('objet_type', sa.String(length=64), nullable=False),
    sa.Column('objet_id', sa.String(length=255), nullable=True),
    sa.Column('avant', sa.JSON(), nullable=True),
    sa.Column('apres', sa.JSON(), nullable=True),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.Column('adresse_ip', sa.String(length=64), nullable=True),
    sa.Column('empreinte_precedente', sa.String(length=64), nullable=False),
    sa.Column('empreinte', sa.String(length=64), nullable=False),
    sa.Column('locataire', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_audit')),
    sa.UniqueConstraint('locataire', 'rang', name='uq_journal_audit_locataire_rang')
    )
    op.create_index('ix_journal_audit_acteur', 'journal_audit', ['locataire', 'acteur'], unique=False)
    op.create_index('ix_journal_audit_objet', 'journal_audit', ['locataire', 'objet_type', 'objet_id'], unique=False)
    op.create_table('habilitation',
    sa.Column('identifiant', sa.String(length=64), nullable=False),
    sa.Column('compte', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('debut', sa.Date(), nullable=False),
    sa.Column('fin', sa.Date(), nullable=True),
    sa.Column('motif', sa.String(length=40), nullable=False),
    sa.Column('accordee_par', sa.String(length=64), nullable=False),
    sa.Column('precision', sa.Text(), nullable=True),
    sa.Column('portee', sa.JSON(), nullable=True),
    sa.Column('locataire', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['compte'], ['compte.identifiant'], name=op.f('fk_habilitation_compte_compte')),
    sa.PrimaryKeyConstraint('identifiant', name=op.f('pk_habilitation'))
    )
    op.create_index('ix_habilitation_compte', 'habilitation', ['locataire', 'compte'], unique=False)
    op.create_table('jeton',
    sa.Column('identifiant', sa.String(length=64), nullable=False),
    sa.Column('empreinte', sa.String(length=64), nullable=False),
    sa.Column('compte', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('emis_le', sa.DateTime(), nullable=False),
    sa.Column('expire_le', sa.DateTime(), nullable=False),
    sa.Column('consomme_le', sa.DateTime(), nullable=True),
    sa.Column('emis_par', sa.String(length=64), nullable=False),
    sa.Column('locataire', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['compte'], ['compte.identifiant'], name=op.f('fk_jeton_compte_compte')),
    sa.PrimaryKeyConstraint('identifiant', name=op.f('pk_jeton')),
    sa.UniqueConstraint('empreinte', name='uq_jeton_empreinte')
    )
    op.create_index('ix_jeton_compte', 'jeton', ['locataire', 'compte'], unique=False)
    op.create_table('session_ouverte',
    sa.Column('identifiant', sa.String(length=64), nullable=False),
    sa.Column('compte', sa.String(length=64), nullable=False),
    sa.Column('ouverte_le', sa.DateTime(), nullable=False),
    sa.Column('expire_le', sa.DateTime(), nullable=False),
    sa.Column('revoquee_le', sa.DateTime(), nullable=True),
    sa.Column('motif_revocation', sa.String(length=40), nullable=True),
    sa.Column('adresse_ip', sa.String(length=64), nullable=True),
    sa.Column('agent', sa.String(length=255), nullable=True),
    sa.Column('renforcee_jusqu_a', sa.DateTime(), nullable=True),
    sa.Column('locataire', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['compte'], ['compte.identifiant'], name=op.f('fk_session_ouverte_compte_compte')),
    sa.PrimaryKeyConstraint('identifiant', name=op.f('pk_session_ouverte'))
    )
    op.create_index('ix_session_compte', 'session_ouverte', ['locataire', 'compte'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """⚠️ Une migration qui supprime des données ne se défait pas : `downgrade`
    rétablit le schéma, jamais le contenu. Sur les tables append-only — journal
    d'audit, accusés de réception —, il n'y a **rien** à défaire."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_compte', table_name='session_ouverte')
    op.drop_table('session_ouverte')
    op.drop_index('ix_jeton_compte', table_name='jeton')
    op.drop_table('jeton')
    op.drop_index('ix_habilitation_compte', table_name='habilitation')
    op.drop_table('habilitation')
    op.drop_index('ix_journal_audit_objet', table_name='journal_audit')
    op.drop_index('ix_journal_audit_acteur', table_name='journal_audit')
    op.drop_table('journal_audit')
    op.drop_index('ix_compte_locataire_etat', table_name='compte')
    op.drop_table('compte')
    op.drop_index('ix_accuse_reception_portail', table_name='accuse_reception')
    op.drop_table('accuse_reception')
    # ### end Alembic commands ###
